# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysportacle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(null=True, related_name='followed_by', to='mysportacle.Profile'),
        ),
    ]
