# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysportacle', '0004_auto_20171108_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
