# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysportacle', '0005_auto_20171108_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')]),
        ),
    ]
