# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='edge',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='expWon',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='gamesWon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='numGames',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='pValue',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='smoothRank',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='trueRank',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
