# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_auto_20171107_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='expWon',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='gamesWon',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='pValue',
        ),
    ]
