# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('name',), 'verbose_name': 'sport', 'verbose_name_plural': 'sports'},
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
