# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20171009_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='slug',
        ),
    ]
