# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
