# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_sport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
