# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20171009_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
