# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('A', 'All Time')], max_length=1)),
                ('position', models.IntegerField()),
                ('numGames', models.IntegerField()),
                ('gamesWon', models.IntegerField()),
                ('expWon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('edge', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('type', '-position'),
            },
        ),
    ]
