# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ('type', '-edge')},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='position',
        ),
    ]
