# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20171107_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='pValue',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
