# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_auto_20171107_0045'),
        ('leaderboard', '0003_leaderboard_pvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranker.Rank'),
        ),
    ]
