# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_leaderboard_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
