# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='selection',
            field=models.CharField(choices=[('V', 'Visitor'), ('H', 'Home')], max_length=1),
        ),
    ]
