# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0002_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('V', 'Visitor'), ('H', 'Home')], default='V', max_length=1),
            preserve_default=False,
        ),
    ]
