# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0004_auto_20171020_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('sport', '-updated')},
        ),
    ]
