# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0005_auto_20171022_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('U', 'Unknown'), ('V', 'Visitor'), ('H', 'Home'), ('T', 'Tie')], max_length=1),
        ),
    ]
