# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0006_auto_20171107_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
                'ordering': ('name',),
            },
        ),
    ]
