# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0007_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
