# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0009_auto_20171113_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pinnacleID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.League'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor',
            field=models.CharField(max_length=200),
        ),
    ]
