# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0010_auto_20171114_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('sport', 'gameTime')},
        ),
        migrations.AlterField(
            model_name='game',
            name='pinnacleID',
            field=models.CharField(max_length=200),
        ),
    ]
